; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3-n16r8]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = lovyan03/LovyanGFX@^1.2.7
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = 16MB.csv
board_build.extra_flags = -DBOARD_HAS_PSRAM -DDISABLE_ALL_LIBRARY_WARNINGS
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = fatfs

; 激进优化 (参考 Anemoia-ESP32)
build_unflags = -Os -O2
build_flags = 
    -Ofast
    -funroll-loops
    -fstrict-aliasing
    -fno-exceptions
    -fno-rtti
    -ffunction-sections
    -fdata-sections
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
board_upload.offset_address = 0x10000
build_src_filter = +<*.cpp> +<*.ino> +<*.h> -<.git/> -<.pio/> -<.DS_Store>
